In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

Data Generation
===

In [16]:
num_samples, num_features = 20, 5

In [17]:
np.random.seed(10)
data = np.random.rand(num_samples, num_features)

Solution
===

In [18]:
print(data)

[[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]
 [0.22479665 0.19806286 0.76053071 0.16911084 0.08833981]
 [0.68535982 0.95339335 0.00394827 0.51219226 0.81262096]
 [0.61252607 0.72175532 0.29187607 0.91777412 0.71457578]
 [0.54254437 0.14217005 0.37334076 0.67413362 0.44183317]
 [0.43401399 0.61776698 0.51313824 0.65039718 0.60103895]
 [0.8052232  0.52164715 0.90864888 0.31923609 0.09045935]
 [0.30070006 0.11398436 0.82868133 0.04689632 0.62628715]
 [0.54758616 0.819287   0.19894754 0.8568503  0.35165264]
 [0.75464769 0.29596171 0.88393648 0.32551164 0.1650159 ]
 [0.39252924 0.09346037 0.82110566 0.15115202 0.38411445]
 [0.94426071 0.98762547 0.45630455 0.82612284 0.25137413]
 [0.59737165 0.90283176 0.53455795 0.59020136 0.03928177]
 [0.35718176 0.07961309 0.30545992 0.33071931 0.7738303 ]
 [0.03995921 0.42949218 0.31492687 0.63649114 0.34634715]
 [0.04309736 0.87991517 0.76324059 0.87809664 0.41750914]
 [0.60557756 0.51346663 0.59783665 0.26221566 0.30087131]
 [0.02539978 0

In [24]:
def standardize(x):
    mu = np.mean(x, axis=0)
    sigma = np.std(x, axis=0)
    return (data - mu) / sigma

std_data = standardize(data)

In [25]:
print(std_data, "\n\n", np.mean(std_data, axis=0), "\n\n", np.std(std_data, axis=0))

[[ 1.13516569 -1.42111972  0.5131182   0.76758966  0.37306299]
 [-1.01445547 -0.88777714  0.98908319 -1.33850972 -1.49134215]
 [ 0.79705939  1.38422007 -1.84902936 -0.09205078  1.80086039]
 [ 0.51058528  0.68746419 -0.76894679  1.38148026  1.35519839]
 [ 0.23532904 -1.05590001 -0.46335424  0.49630297  0.11545342]
 [-0.19154917  0.37467234  0.06105786  0.41006546  0.83911946]
 [ 1.26851326  0.0855486   1.54470807 -0.79308538 -1.48170785]
 [-0.71590759 -1.14068118  1.24473161 -1.78253078  0.95388452]
 [ 0.25515971  0.98083471 -1.11754281  1.16013619 -0.29446003]
 [ 1.06958663 -0.59330221  1.45200624 -0.7702855  -1.14281286]
 [-0.35471949 -1.20241633  1.21631356 -1.40375641 -0.14690566]
 [ 1.81538401  1.48718864 -0.15213824  1.04849938 -0.75027357]
 [ 0.45097901  1.23213329  0.14140804  0.19136631 -1.71433432]
 [-0.49375035 -1.24406828 -0.71799069 -0.75136535  1.62453835]
 [-1.74146923 -0.19164907 -0.682478    0.35954303 -0.31857601]
 [-1.72912608  1.16320132  0.99924854  1.23732688  0.00